import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MicrosoftClarity from "./components/MicrosoftClarity";
import Visitor from "./components/visitor";
import Script from "next/script";
import ScrollTracker from "./components/ScrollTracker";
import GAListener from "./components/GAListener";
import CustomCursor from "./components/CustomCursor";
import { Suspense } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import SmoothScroll from "./components/SmoothScroll";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=G-R7RDP2W2QZ`}
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-R7RDP2W2QZ', {
              page_path: window.location.pathname,
            });
          `}
        </Script>


      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MicrosoftClarity />
        <Suspense fallback={null}>
          <GAListener />
        </Suspense>

        <SmoothScroll>
          <CustomCursor />
          <ScrollTracker />
          {children}
          <Visitor />
        </SmoothScroll>
      </body>
    </html>
  );
}
