import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Visitor from "./components/visitor";
import ScrollTracker from "./components/ScrollTracker";
import GAListener from "./components/GAListener";
import { Suspense } from "react";
import { GoogleAnalytics } from "next-google-analytics";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleAnalytics gaId="G-R7RDP2W2QZ" />

        <Suspense fallback={null}>
          <GAListener />
        </Suspense>

        <ScrollTracker />
        {children}
        <Visitor />
      </body>
    </html>
  );
}
